schema_version: 1

project_id: fmd-patho
subproject_id: sequence-map

title: Mapping Virus Diversity and Variation
summary: >
  Sequencemap converts aligned viral sequences and sampling geographic coordinates into PCA, DAPC, and other
location-level summaries and optional spatial predictions of ordination-axis scores across geographic space.

lead:
  name: John Humphreys
  github: JMHumphreys

status: active
current_focus: Adding functionality for estimation of allele diversity.

repository:
  canonical: geoepi/sequence-map
  upstream: null

compute:
  - local

next_milestone:
  description: Estimation of allele diversity
  target: 2026-09-01
